spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

org:
  telegram:
    cbrexchangebot:
      token: ${TG_TOKEN}
      name: CbrExcnageRateBot

---
spring:
  config:
    activate:
      on-profile: test