spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

org:
  telegram:
    cbrexchangebot:
      token: 6757729128:AAE9rvw218gfydoitQbt50YRUcme6eimHak
      name: CbrExcnageRateBot

---
spring:
  config:
    activate:
      on-profile: test